http:
  addr: 127.0.0.1:8080 # HTTP 服务监听地址
grpc:
  addr: 127.0.0.1:8000 # GRPC 服务监听的地址

mysql:
  host: 127.0.0.1:3306 # 数据库主机地址
  database: krm # 数据库名称
  username: root # 数据库用户名
  password: s0kewK7Ph#0AE9IX # 数据库密码